version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: nestjs-tutorial-postgres
        environment:
            POSTGRES_DB: ${PG_NAME}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - ${PG_PORT}:5432
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
